name: Legacy Ops Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d').$env:GITHUB_RUN_NUMBER"
    
    - name: Test with environment variables
      run: echo $TAG_NAME
      env:
        TAG_NAME: ${{ steps.date.outputs.date }}
      
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
    
    - name: Create Build Directory
      run: mkdir ./Artifacts/ops

    - name: Restore Packages
      run: nuget restore Ops.sln

    - name: Build Solution
      run: |
        msbuild.exe /t:Rebuild /p:PublishProtocol="FileSystem" /p:Configuration=Release /p:OutputPath=./bin /p:DeleteExistingFiles=True /p:platform="Any CPU"
    - name: Run Tests
      run: ./packages/NUnit.org/nunit-console/nunit3-console.exe  ./Tests/bin/Ops.Test.dll --where cat==CI --work=.
    
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.6
      with:
        version: latest
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: Release ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false  